rules = [
  RemoveUnused,
  ExplicitResultTypes,
  ProcedureSyntax,
  OrganizeImports
]

RemoveUnused.imports = false
OrganizeImports.groupedImports = Merge
OrganizeImports.importSelectorsOrder = SymbolsFirst
OrganizeImports.groups = [
  "re:javax?\\.",
  "scala.",
  "org.slf4j.",
  "cats.",
  "*",
  "io.github.andy327."
]
